### ISSUE TITLE
Tornar a justificativa obrigatória.

### ISSUE THREAD

**Issue by allanrodrigues** [dextra/dexboard#11]
Hoje, fui testar a atribuição de alguma marcação a um indicador do projeto e, quando cliquei, o sistema imediatamente atualizeou o indicador, apagando o post anterior (que era bem bacana).

Isso não está intuitivo, pois na minha percepção eu tinha claro que um pedido de confirmação seria feito. Minha sugestão é: para não ter que solicitar confirmação (o que seria um popup sobre outro popup), uma saída simples é obrigar o preenchimento da justificativa. Dessa forma, cliques "indevidos/sem querer" seriam evitados, além de obrigar o ator a não fazer uma análise evasiva, sem argumentos.

**Comment by GiovaniMFMurari** [comment]
Fechando a issue devido à sua idade.
