### ISSUE TITLE
Tempo de rotação dos quadros

### ISSUE THREAD

**Issue by leguimas** [dextra/dexboard#12]
O tempo de rotação entre os "quadros" (conjunto de projetos) do DexBoard está bem curto hoje. Aqui no Desenvolvimento de Negócios, aonde temos a TV exibindo o quadro direto, a cada poucos segundos o quadro muda o que acaba causando um incômodo e, muitas vezes, mal dá pra ver ou interagir com as informações.

Seria legal colocar um parâmetro (que nem o from), com um valor default, aonde você pudesse especificar o intervalo desejado. 

dexboard-reload.appspot.com?from=TV&t=300   (os paineis seriam trocados a cada 5 minutos)

**Comment by GiovaniMFMurari** [comment]
Fechando a issue devido à sua idade.
